### Validation with POST method
POST http://localhost:5260/Validation/Add
Content-Type: application/json

{
  "number1": 999
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not a bad request");
    });
%}
